### ISSUE TITLE
Software centre (Xubuntu 17.10) shows KITScenarist's license as "proprietary"

### ISSUE THREAD

**Issue by WPFilmmaker** [dimkanovikov/KITScenarist#579]
I checked your license on github and it says GPL 3.0 however on the software centre it is labelled as "proprietary". You probably want to ask the devs to fix it. The version I use is 0.7.2.beta5.

**Comment by dimkanovikov** [comment]
Hello, my friend. Look like we missed Licence key in packages... Thanks, will be fixed!

**Comment by WPFilmmaker** [comment]
Great news! And thank your geat work with KitScenarist! I installed it yesterday and it seems to be working pefectly, I will definitively report any bug i find :)

**Comment by dimkanovikov** [comment]
You are welcome! Thanks a lot! :)

**Comment by dimkanovikov** [comment]
Hey, @WPFilmmaker we added copyright file with a license to the packages. When release will be published I notice you, to check software center behavior with a new package.

**Comment by WPFilmmaker** [comment]
@dimkanovikov Thanks!

**Comment by dimkanovikov** [comment]
Hey @WPFilmmaker! We published the update, please check what software center will tell you now.

**Comment by WPFilmmaker** [comment]
@dimkanovikov Thanks! I doubled checked by unistalling KITScenarist and then searching it again BUT it disappeared from the software store! I tried searching for "KITScenarist", "Kit Scenarist", "Scenarist" but nothing... do you know what happened?

**Comment by dimkanovikov** [comment]
Hm... But our app doesn't present in the Ubuntu repositories, so you can install it just one way - after manually downloading it from our website.

**Comment by WPFilmmaker** [comment]
@dimkanovikov Actually you are right, sorry for my mistake, I installed the latest beta but it still shows "proprietary", screenshot here: https://s18.postimg.org/3n35vjvrd/kits.png

**Comment by dimkanovikov** [comment]
@WPFilmmaker possibly it is so because we don't have a package in the repo. I check it with other apps and behavior reproduced... It's funny that package manager ignores license from the package file :)

**Comment by WPFilmmaker** [comment]
@dimkanovikov It is a pity because It creates confusion in the users and does not make justice to you devs :-/ could a temporary fix be adding a description saying "free and open source screen writing software?". In the long term really hope to see #614 resolved :-)

**Comment by dimkanovikov** [comment]
@WPFilmmaker good idea!
