### ISSUE TITLE
Custom dictionary does not save

### ISSUE THREAD

**Issue by imgforge** [dimkanovikov/KITScenarist#673]
[dictionary.zip](https://github.com/dimkanovikov/KITScenarist/files/2057872/dictionary.zip)

Custom dictionary does not save.  See example.

**Comment by dimkanovikov** [comment]
Thanks. Will be rechecked.

**Comment by dimkanovikov** [comment]
@imgforge I checked it and it works correctly. What version are you use and what operating system?

**Comment by imgforge** [comment]
0.7.2 Beta 7
Windows 10
English

**Comment by dimkanovikov** [comment]
Are you use the installed version of the application or portable?

**Comment by imgforge** [comment]
The installed version

**Comment by imgforge** [comment]
And also, remember the screenshots I sent where words containing punctuation, symbols, etc. will not save - i.e., screen-play would show a red line beneath and cannot be added to dictionary.

**Comment by dimkanovikov** [comment]
Hm... Can you check the file **C:\Users\USER_NAME\AppData\Local\DimkaNovikov labs\Scenarist\Hunspell\UserDictionary.dict**. It should contain words that you add to dictionary from the app.

**Comment by dimkanovikov** [comment]
Bug with punctuation was fixed recently at #645

**Comment by imgforge** [comment]
Yes - words are there.  Last saved today.  Let me check one thing.

**Comment by imgforge** [comment]
Custom dictionary saves as soon as I add a word.  Everything working there -- Closed the program, rebooted, rechecked the file - file integrity is fine.  The disconnect is further up the chain - possibly the app trying to read the file?  Either way, still having the same problem as noted in video.

**Comment by imgforge** [comment]
@dimkanovikov I noticed UserDictionary.dict has spaces between some of the words -- Could that cause the problem?  See attached.
![2018-06-13_10-11-55](https://user-images.githubusercontent.com/13594657/41356779-942376a4-6ef2-11e8-8d2d-e6876f517c62.jpg)

**Comment by imgforge** [comment]
There also a few of the '?'.  This was the result of the igbo language words being added.
![2018-06-13_10-15-45](https://user-images.githubusercontent.com/13594657/41356931-fbb7629e-6ef2-11e8-86a2-66552a481978.jpg)

**Comment by imgforge** [comment]
That was the problem - the unknown characters - I removed them from the file, saved, restarted Scenarist and it worked fine.

**Comment by dimkanovikov** [comment]
Thanks a lot for your find! We lacked UTF support when words was added to the user dictionary. Now it will work like a charm!

**Comment by imgforge** [comment]
Excellent!
